# Generated by Django 6.0.5 on 2026-06-06 04:44

from django.db import migrations, models


def generate_employee_ids(apps, schema_editor):
    """Generate employee IDs for existing employees"""
    Employee = apps.get_model('myapp', 'Employee')
    for index, employee in enumerate(Employee.objects.all().order_by('id'), start=1):
        employee.employee_id = f"EMP{index:03d}"
        employee.save()


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(default='', editable=False, max_length=10),
        ),
        migrations.RunPython(generate_employee_ids),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(default='', editable=False, max_length=10, unique=True),
        ),
    ]
